version: "3"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
